# Basic website configuration. Only change the title.
baseURL = "/"
languageCode = "en-us"
title = "Alice in Wonderland"
# Use the webcomic theme.
theme = "webcomic-theme"


# Hamburger menu config: links to pages of the site.
# name = "Display Name"
# url = "/relative-url"
[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Archive"
  url = "/comic"


# Menu bar config: links to social media
# Use the "pre" field to display a FontAwesome icon: https://fontawesome.com/v4.7.0/icons/#brand
# name = "Display Name"
# url = "https://link.com/me"
# pre = "<i class='FONTAWESOME ICON NAME HERE'></i>"
[[menu.social]]
    name = "GitHub"
    url = "https://github.com/arsoward/webcomic-theme"
    pre = "<i class='fab fa-github'></i>"


# Footer config: Any other links
# name = "Display Name"
# url = "https://link.com/me" OR "/relative-link"
[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Theme"
  url = "https://github.com/arsoward/webcomic-theme"
