# Basic website configuration. Only change the title.
baseURL = "/"
languageCode = "en-us"
title = "Wild Rose"
# Use the webcomic theme.
theme = "webcomic-theme"


# Menu bar config: link to a scalable transparent logo.
# If you don't have one, comment out this config. The menu bar will use the title configured above.
[[menu.logo]]
  pre = "<img src='/img/logo.png' id='logo' alt='logo'>"

# Hamburger menu config: links to pages of the site.
# name = "Display Name"
# url = "/relative-url"
# To add more content pages, make a blog post and add the link here.
# E.g for a blog post called "Comissions Open": 
# [[menu.main]]
#   name = "Comissions"
#   url = "/blog/comissions-open"
[[menu.main]]
  name = "About"
  url = "/about"

[[menu.main]]
  name = "Archive"
  url = "/comic"


# Menu bar config: links to social media
# Use the "pre" field to display a FontAwesome icon: https://fontawesome.com/v4.7.0/icons/#brand
# name = "Display Name"
# url = "https://link.com/me"
# pre = "<i class='FONTAWESOME ICON NAME HERE'></i>"
[[menu.social]]
    name = "Tumblr"
    url = "https://karinamorenoart.tumblr.com/"
    pre = "<i class='fab fa-tumblr'></i>"

[[menu.social]]
    name = "Twitter"
    url = "https://twitter.com/karinamorenoart"
    pre = "<i class='fab fa-twitter'></i>"

[[menu.social]]
    name = "Etsy"
    url = "https://www.etsy.com/shop/KarinaMorenoArt"
    pre = "<i class='fab fa-etsy'></i>"

[[menu.social]]
    name = "Patreon"
    url = "https://www.patreon.com/karinamorenoart"
    pre = "<i class='fab fa-patreon'></i>"

[[menu.social]]
    name = "Twitch"
    url = "https://m.twitch.tv/karinamorenoart/profile"
    pre = "<i class='fab fa-twitch'></i>"

[[menu.social]]
    name = "Instagram"
    url = "https://www.instagram.com/KarinaMorenoArt/"
    pre = "<i class='fab fa-instagram'></i>"


# Footer config: Any other links
# name = "Display Name"
# url = "https://link.com/me" OR "/relative-link"
[[menu.footer]]
  name = "About"
  url = "/about"

[[menu.footer]]
  name = "Theme"
  url = "https://github.com/arsoward/webcomic-theme"
